### ISSUE TITLE
hfst-tokeniser gives "<>" "" ? (analysis of space) after CLB

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-vep#1]
The error occurs with hfst-tokeniser -cg. Using -x (xerox output) instead, what happens is that the word preceeding the CLB gets an empty analysis (see below for -x).  The behaviour is clearly linked to linear order: Feeding "Oli se, " to hfst-tokenise -x gives an empty analysis for "se", whereas feeding "Se oli, " gives an empty analysis for "oli" instead (see final -x esample below).

The uneasy thing with this, except for the fact that this is noise in the vep output, is that I (we?) do not understand what is going on.

```
$ e "Oli se, völ."|hfst-tokenise -cg tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
"<Oli>"
	"olda" V Ind Prt Sg3 <W:0.0>
: 
"<se>"
	"se" Pron Dem Sg Nom <W:0.0>
"<,>"
	"," CLB <W:0.0>
"<>"
	"" ?
: 
"<völ>"
	"vö" N Sg Ade <W:0.0>
	"völ" Adv Temp <W:0.0>
"<.>"
	"." CLB <W:0.0>
"<>"
	"" ?
:\n
"<>"
	"" ?
$ e "Oli se, völ."|hfst-tokenise -x tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
Oli	
Oli	olda V Ind Prt Sg3

se	se Pron Dem Sg Nom
se	

,	, CLB

	

völ	vö N Sg Ade
völ	völ Adv Temp
völ	

.	. CLB



$ e "Se oli, völ."|hfst-tokenise -x tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
Se	
Se	se Pron Dem Sg Nom

oli	olda V Ind Prt Sg3
oli	

,	, CLB

	

völ	vö N Sg Ade
völ	völ Adv Temp
völ	

.	. CLB
```

Straight xerox analysis gives no superfluous analyses, so this is a flaw in the tokeniser:

``` 
	
$ huvep
se
se	se+Pron+Dem+Sg+Nom	0,000000

völ
völ	vö+N+Sg+Ade	0,000000
völ	völ+Adv+Temp	0,000000
```

**Comment by snomos** [comment]
The bug is not in hfst-tokenise, it is in the fst, as demoed by this:

```sh
hfst-lookup -q src/analyser-gt-desc.hfstol 
se
se	se+Pron+Dem+Sg+Nom	0,000000


		0,000000

völ
völ	vö+N+Sg+Ade	0,000000
völ	völ+Adv+Temp	0,000000
```

That empty analysis with weight `0,000000` is coming after a newline, ie empty input.

The likely cause is that something is turned into an epsilon-like entity, without being an epsilon in the technical sense.

**Comment by snomos** [comment]
The error is in the lexc code somewhere:

```sh
hfst-lookup -q src/fst/lexicon.hfst

		0,000000

^C
```

**Comment by Trondtr** [comment]
OK, I'll have a look.

**Comment by snomos** [comment]
Fixed:

```sh
echo "Oli se, völ."|hfst-tokenise -cg tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
"<Oli>"
	"olda" V Ind Prt Sg3 <W:0.0>
: 
"<se>"
	"se" Pron Dem Sg Nom <W:0.0>
"<,>"
	"," CLB <W:0.0>
: 
"<völ>"
	"vö" N Sg Ade <W:0.0>
	"völ" Adv Temp <W:0.0>
"<.>"
	"." CLB <W:0.0>
:\n
```
